spring.application.name=ISTE240-604-Group4

# adding config for connecting to our db
spring.datasource.url=jdbc:mysql://localhost:3307/iste240?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234567

# if columns/tables don't already exist in db
spring.jpa.hibernate.ddl-auto=update

# dialect for SQL -> if db throws an error
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# makes sure tables are created BEFORE the SQL runs
spring.jpa.defer-datasource-initialization=true

# tells Spring where to find the seed file
spring.sql.init.data-locations=classpath:data.sql

# ensures data.sql always runs on startup
spring.sql.init.mode=always